// Titles for Emojiyle Anlat. t = shown title, a = other accepted answers (English/original names).
const EMO_ITEMS = {
  film: { name: 'Film', items: [
    {"t": "Titanik", "a": ["titanic"]},
    {"t": "Aslan Kral", "a": ["lion king", "the lion king"]},
    {"t": "Harry Potter"},
    {"t": "Örümcek Adam", "a": ["spiderman", "spider man"]},
    {"t": "Buz Devri", "a": ["ice age"]},
    {"t": "Shrek"},
    {"t": "Karayip Korsanları", "a": ["pirates of the caribbean", "jack sparrow"]},
    {"t": "Yüzüklerin Efendisi", "a": ["lord of the rings"]},
    {"t": "Hobbit", "a": ["the hobbit"]},
    {"t": "Avatar"},
    {"t": "Jurassic Park", "a": ["jurassic world"]},
    {"t": "Kayıp Balık Nemo", "a": ["nemo", "finding nemo"]},
    {"t": "Kayıp Balık Dori", "a": ["dory", "finding dory"]},
    {"t": "Oyuncak Hikayesi", "a": ["toy story"]},
    {"t": "Karlar Ülkesi", "a": ["frozen"]},
    {"t": "Hızlı ve Öfkeli", "a": ["fast and furious", "fast furious"]},
    {"t": "Matrix"},
    {"t": "Batman", "a": ["kara şövalye", "the dark knight", "dark knight"]},
    {"t": "Süpermen", "a": ["superman"]},
    {"t": "Yıldız Savaşları", "a": ["star wars"]},
    {"t": "Recep İvedik"},
    {"t": "Hababam Sınıfı"},
    {"t": "Arabalar", "a": ["cars"]},
    {"t": "Minyonlar", "a": ["minions"]},
    {"t": "Çılgın Hırsız", "a": ["despicable me"]},
    {"t": "Kung Fu Panda"},
    {"t": "Madagaskar", "a": ["madagascar"]},
    {"t": "Alaaddin", "a": ["aladdin"]},
    {"t": "King Kong"},
    {"t": "Godzilla"},
    {"t": "Joker"},
    {"t": "Barbie"},
    {"t": "Ters Yüz", "a": ["inside out"]},
    {"t": "Terminatör", "a": ["terminator"]},
    {"t": "Demir Adam", "a": ["iron man"]},
    {"t": "Yenilmezler", "a": ["avengers", "the avengers"]},
    {"t": "Kaptan Amerika", "a": ["captain america"]},
    {"t": "Thor"},
    {"t": "Hulk"},
    {"t": "Kara Panter", "a": ["black panther"]},
    {"t": "Deadpool"},
    {"t": "Venom"},
    {"t": "Doktor Strange", "a": ["doctor strange"]},
    {"t": "Galaksinin Koruyucuları", "a": ["guardians of the galaxy"]},
    {"t": "Karınca Adam", "a": ["ant man", "antman"]},
    {"t": "Wonder Woman"},
    {"t": "Aquaman"},
    {"t": "X-Men"},
    {"t": "Fantastik Dörtlü", "a": ["fantastic four"]},
    {"t": "Transformers"},
    {"t": "Jaws", "a": ["denizkızı"]},
    {"t": "Başlangıç", "a": ["inception"]},
    {"t": "Truman Show", "a": ["the truman show"]},
    {"t": "Esaretin Bedeli", "a": ["shawshank redemption", "the shawshank redemption"]},
    {"t": "Baba", "a": ["the godfather", "godfather"]},
    {"t": "Forrest Gump"},
    {"t": "Yıldızlararası", "a": ["interstellar"]},
    {"t": "Dövüş Kulübü", "a": ["fight club"]},
    {"t": "Gladyatör", "a": ["gladiator"]},
    {"t": "Kuzuların Sessizliği", "a": ["silence of the lambs", "the silence of the lambs"]},
    {"t": "Ucuz Roman", "a": ["pulp fiction"]},
    {"t": "Geleceğe Dönüş", "a": ["back to the future"]},
    {"t": "Yeşil Yol", "a": ["the green mile", "green mile"]},
    {"t": "Evde Tek Başına", "a": ["home alone"]},
    {"t": "Rocky"},
    {"t": "Rambo"},
    {"t": "E.T.", "a": ["et"]},
    {"t": "Hayalet Avcıları", "a": ["ghostbusters"]},
    {"t": "Indiana Jones"},
    {"t": "Mumya", "a": ["the mummy", "mummy"]},
    {"t": "Görevimiz Tehlike", "a": ["mission impossible"]},
    {"t": "James Bond", "a": ["007"]},
    {"t": "John Wick"},
    {"t": "Oppenheimer"},
    {"t": "Dune"},
    {"t": "Parazit", "a": ["parasite"]},
    {"t": "Hachiko", "a": ["hachi"]},
    {"t": "Yukarı Bak", "a": ["up"]},
    {"t": "Ratatuy", "a": ["ratatouille"]},
    {"t": "WALL-E", "a": ["wall e", "walle"]},
    {"t": "Coco"},
    {"t": "Zootropolis", "a": ["zootopia"]},
    {"t": "Moana"},
    {"t": "Rapunzel", "a": ["tangled"]},
    {"t": "Güzel ve Çirkin", "a": ["beauty and the beast"]},
    {"t": "Külkedisi", "a": ["cinderella"]},
    {"t": "Pamuk Prenses", "a": ["snow white"]},
    {"t": "Uyuyan Güzel", "a": ["sleeping beauty"]},
    {"t": "Küçük Deniz Kızı", "a": ["the little mermaid", "little mermaid"]},
    {"t": "Mulan"},
    {"t": "Pinokyo", "a": ["pinocchio"]},
    {"t": "Dumbo"},
    {"t": "Bambi"},
    {"t": "Herkül", "a": ["hercules"]},
    {"t": "Tarzan"},
    {"t": "Pocahontas"},
    {"t": "101 Dalmaçyalı", "a": ["101 dalmatians", "101 dalmaçyalı köpek"]},
    {"t": "Canavarlar Şirketi", "a": ["monsters inc", "monsters"]},
    {"t": "İnanılmaz Aile", "a": ["the incredibles", "incredibles"]},
    {"t": "Ejderhanı Nasıl Eğitirsin", "a": ["how to train your dragon"]},
    {"t": "Çizmeli Kedi", "a": ["puss in boots"]},
    {"t": "Rio"},
    {"t": "Bolt"},
    {"t": "Otel Transilvanya", "a": ["hotel transylvania"]},
    {"t": "Oyunbozan Ralph", "a": ["wreck it ralph", "ralph"]},
    {"t": "Sonic"},
    {"t": "Süper Mario", "a": ["super mario", "mario"]},
    {"t": "Angry Birds"},
    {"t": "G.O.R.A.", "a": ["gora"]},
    {"t": "Arog"},
    {"t": "Vizontele"},
    {"t": "Babam ve Oğlum"},
    {"t": "Eşkıya"},
    {"t": "Organize İşler"},
    {"t": "Düğün Dernek"},
    {"t": "Ayla"},
    {"t": "Kelebeğin Rüyası"},
    {"t": "Hokkabaz"},
    {"t": "Tosun Paşa"},
    {"t": "Süt Kardeşler"},
    {"t": "Kibar Feyzo"},
    {"t": "Neşeli Günler"},
    {"t": "Çöpçüler Kralı"},
    {"t": "Yahşi Batı"},
    {"t": "Kolpaçino"},
    {"t": "Dabbe"},
    {"t": "Müslüm"},
    {"t": "7. Koğuştaki Mucize", "a": ["yedinci koğuştaki mucize", "7 koğuştaki mucize", "koğuştaki mucize"]},
    {"t": "Testere", "a": ["saw"]},
    {"t": "Korku Seansı", "a": ["the conjuring", "conjuring"]},
    {"t": "Annabelle"},
    {"t": "It", "a": ["o"]},
    {"t": "Çığlık", "a": ["scream"]},
    {"t": "Şeytan Çıkarıcı", "a": ["the exorcist", "exorcist"]},
    {"t": "Cinnet", "a": ["the shining", "shining"]},
    {"t": "Ölü Ozanlar Derneği", "a": ["dead poets society"]},
    {"t": "Yedi", "a": ["se7en", "seven"]},
    {"t": "Prestij", "a": ["the prestige", "prestige"]},
    {"t": "Zindan Adası", "a": ["shutter island"]},
    {"t": "Wall Street'in Kurdu", "a": ["the wolf of wall street", "wolf of wall street"]},
    {"t": "Yakalarsan Seninim", "a": ["catch me if you can"]},
    {"t": "Er Ryan'ı Kurtarmak", "a": ["saving private ryan"]},
    {"t": "Narnia Günlükleri", "a": ["narnia", "chronicles of narnia"]},
    {"t": "Açlık Oyunları", "a": ["hunger games", "the hunger games"]},
    {"t": "Alacakaranlık", "a": ["twilight"]},
    {"t": "Mad Max"},
    {"t": "Star Trek", "a": ["uzay yolu"]},
    {"t": "Yaratık", "a": ["alien"]},
    {"t": "Predator", "a": ["av"]},
    {"t": "Kara Kuğu", "a": ["black swan"]},
    {"t": "La La Land"},
    {"t": "Mamma Mia"},
    {"t": "Grease"},
    {"t": "Kirli Dans", "a": ["dirty dancing"]},
    {"t": "Hayalet", "a": ["ghost"]},
    {"t": "Özel Bir Kadın", "a": ["pretty woman"]},
    {"t": "Maske", "a": ["the mask", "mask"]},
    {"t": "Ace Ventura"},
    {"t": "Yalancı Yalancı", "a": ["liar liar"]},
    {"t": "Aman Tanrım", "a": ["bruce almighty"]},
    {"t": "Karate Kid"},
    {"t": "Gece Müzede", "a": ["night at the museum"]},
    {"t": "Jumanji"},
    {"t": "Charlie'nin Çikolata Fabrikası", "a": ["charlie and the chocolate factory", "çikolata fabrikası", "willy wonka", "wonka"]},
    {"t": "Alice Harikalar Diyarında", "a": ["alice in wonderland"]},
    {"t": "Edward Makaseller", "a": ["edward scissorhands"]},
    {"t": "Grinch"},
    {"t": "Polar Ekspres", "a": ["polar express"]},
    {"t": "Paddington"},
    {"t": "Beethoven"},
    {"t": "Takip", "a": ["taken"]},
    {"t": "Zor Ölüm", "a": ["die hard"]},
    {"t": "Kill Bill"},
    {"t": "Soysuzlar Çetesi", "a": ["inglourious basterds"]},
    {"t": "Django"},
    {"t": "Piyanist", "a": ["the pianist", "pianist"]},
    {"t": "Schindler'in Listesi", "a": ["schindlers list"]},
    {"t": "Hayat Güzeldir", "a": ["life is beautiful"]},
    {"t": "Amelie"},
    {"t": "Matilda"},
    {"t": "Tenet"},
    {"t": "Top Gun"},
    {"t": "Terminal", "a": ["the terminal"]},
    {"t": "Yeni Hayat", "a": ["cast away"]},
    {"t": "Ben Efsaneyim", "a": ["i am legend"]},
    {"t": "Benjamin Button'ın Tuhaf Hikayesi", "a": ["benjamin button"]},
    {"t": "300"},
    {"t": "Truva", "a": ["troy"]},
    {"t": "Cesur Yürek", "a": ["braveheart"]},
    {"t": "Son Samuray", "a": ["the last samurai", "last samurai"]},
    {"t": "Robin Hood"},
    {"t": "Zorro"},
    {"t": "Üç Silahşörler", "a": ["the three musketeers", "üç silahşorler"]},
    {"t": "Görünmez Adam", "a": ["invisible man", "the invisible man"]},
    {"t": "Frankenstein"},
    {"t": "Drakula", "a": ["dracula"]},
    {"t": "Hayalet Gemi", "a": ["ghost ship"]},
    {"t": "Gremlinler", "a": ["gremlins"]},
    {"t": "Ölümcül Silah", "a": ["lethal weapon"]},
    {"t": "Mavi Göl", "a": ["the blue lagoon", "blue lagoon"]},
    {"t": "Saatleri Ayarlama Enstitüsü"},
    {"t": "Sihirbazlar Çetesi", "a": ["now you see me"]},
    {"t": "Sherlock Holmes"},
    {"t": "Kuşlar", "a": ["the birds", "birds"]},
    {"t": "Sapık", "a": ["psycho"]},
    {"t": "Hayvan Çiftliği", "a": ["animal farm"]},
    {"t": "Minecraft Filmi", "a": ["minecraft"]},
    {"t": "Wicked"},
    {"t": "Arı Filmi", "a": ["bee movie"]},
    {"t": "Spirit"},
    {"t": "Lilo ve Stitch", "a": ["lilo and stitch", "lilo stitch", "stitch"]},
    {"t": "Kurtlar Vadisi Irak"},
  ] },
  dizi: { name: 'Dizi', items: [
    {"t": "Kurtlar Vadisi"},
    {"t": "Leyla ile Mecnun"},
    {"t": "Squid Game", "a": ["kalamar oyunu"]},
    {"t": "Stranger Things"},
    {"t": "Prison Break"},
    {"t": "Game of Thrones", "a": ["taht oyunları"]},
    {"t": "House of the Dragon", "a": ["ejderha hanedanı"]},
    {"t": "Breaking Bad"},
    {"t": "Better Call Saul"},
    {"t": "Avrupa Yakası"},
    {"t": "Ezel"},
    {"t": "Muhteşem Yüzyıl"},
    {"t": "Friends"},
    {"t": "Sherlock"},
    {"t": "La Casa de Papel", "a": ["money heist", "para soygunu"]},
    {"t": "Wednesday"},
    {"t": "Peaky Blinders"},
    {"t": "Diriliş Ertuğrul"},
    {"t": "Kuruluş Osman"},
    {"t": "Behzat Ç", "a": ["behzat"]},
    {"t": "The Walking Dead", "a": ["walking dead"]},
    {"t": "The Mentalist", "a": ["mentalist"]},
    {"t": "Dexter"},
    {"t": "Lost", "a": ["kayıp"]},
    {"t": "House", "a": ["dr house", "house md"]},
    {"t": "Grey's Anatomy", "a": ["greys anatomy"]},
    {"t": "How I Met Your Mother", "a": ["himym"]},
    {"t": "The Office", "a": ["office"]},
    {"t": "Brooklyn Nine-Nine", "a": ["brooklyn 99", "brooklyn nine nine"]},
    {"t": "The Big Bang Theory", "a": ["big bang theory"]},
    {"t": "Two and a Half Men", "a": ["iki buçuk adam"]},
    {"t": "Dark"},
    {"t": "The Witcher", "a": ["witcher"]},
    {"t": "Vikings"},
    {"t": "The Crown"},
    {"t": "Black Mirror"},
    {"t": "Sons of Anarchy"},
    {"t": "Narcos"},
    {"t": "The Boys"},
    {"t": "The Last of Us"},
    {"t": "The Mandalorian", "a": ["mandalorian"]},
    {"t": "Loki"},
    {"t": "Lucifer"},
    {"t": "Supernatural"},
    {"t": "Vampir Günlükleri", "a": ["vampire diaries", "the vampire diaries"]},
    {"t": "Gossip Girl"},
    {"t": "Umutsuz Ev Kadınları", "a": ["desperate housewives"]},
    {"t": "Sex and the City"},
    {"t": "Suits"},
    {"t": "Mr. Robot", "a": ["mr robot"]},
    {"t": "Westworld"},
    {"t": "Çernobil", "a": ["chernobyl"]},
    {"t": "Doctor Who"},
    {"t": "Twin Peaks"},
    {"t": "Gizli Dosyalar", "a": ["x files", "the x files"]},
    {"t": "24"},
    {"t": "Heroes"},
    {"t": "Fringe"},
    {"t": "CSI"},
    {"t": "Bones"},
    {"t": "Castle"},
    {"t": "The Sopranos", "a": ["sopranos"]},
    {"t": "The Wire"},
    {"t": "Mr. Bean", "a": ["mr bean", "bay bean"]},
    {"t": "Seinfeld"},
    {"t": "Modern Family"},
    {"t": "Elite"},
    {"t": "Lupin"},
    {"t": "Emily in Paris", "a": ["emily paris"]},
    {"t": "Bridgerton"},
    {"t": "You"},
    {"t": "13 Reasons Why", "a": ["13 sebep"]},
    {"t": "Riverdale"},
    {"t": "The Umbrella Academy", "a": ["umbrella academy"]},
    {"t": "Sex Education"},
    {"t": "Ozark"},
    {"t": "The Flash", "a": ["flash"]},
    {"t": "Arrow"},
    {"t": "Smallville"},
    {"t": "Gotham"},
    {"t": "Daredevil"},
    {"t": "Hannibal"},
    {"t": "True Detective"},
    {"t": "Fargo"},
    {"t": "Cobra Kai"},
    {"t": "Yellowstone"},
    {"t": "Succession"},
    {"t": "The Good Doctor", "a": ["good doctor"]},
    {"t": "Severance"},
    {"t": "Shōgun", "a": ["shogun"]},
    {"t": "Bir Zamanlar Çukurova"},
    {"t": "Çukur"},
    {"t": "Kara Sevda"},
    {"t": "Aşk-ı Memnu", "a": ["aşkı memnu"]},
    {"t": "Yaprak Dökümü"},
    {"t": "Gümüş"},
    {"t": "Yabancı Damat"},
    {"t": "Arka Sokaklar"},
    {"t": "Sihirli Annem"},
    {"t": "Bez Bebek"},
    {"t": "Cennet Mahallesi"},
    {"t": "Çocuklar Duymasın"},
    {"t": "Yalan Dünya"},
    {"t": "Kardeş Payı"},
    {"t": "Kavak Yelleri"},
    {"t": "Aşk Laftan Anlamaz"},
    {"t": "Kiraz Mevsimi"},
    {"t": "Masumlar Apartmanı"},
    {"t": "Yargı"},
    {"t": "Kızılcık Şerbeti"},
    {"t": "Yalı Çapkını"},
    {"t": "Söz"},
    {"t": "İçerde"},
    {"t": "Poyraz Karayel"},
    {"t": "Şahsiyet"},
    {"t": "Bir Başkadır"},
    {"t": "Hakan: Muhafız", "a": ["hakan muhafız", "muhafız"]},
    {"t": "Kara Para Aşk"},
    {"t": "Hercai"},
    {"t": "Sen Çal Kapımı"},
    {"t": "Hayat Bilgisi"},
    {"t": "Selena"},
    {"t": "Akasya Durağı"},
    {"t": "Bizimkiler"},
    {"t": "Seksenler"},
    {"t": "1 Kadın 1 Erkek", "a": ["bir kadın bir erkek"]},
    {"t": "Gibi"},
    {"t": "Kurtlar Vadisi Pusu"},
    {"t": "Ramo"},
    {"t": "Erşan Kuneri"},
    {"t": "Kuzey Güney"},
    {"t": "Fatmagül'ün Suçu Ne?", "a": ["fatmagülün suçu ne", "fatmagül"]},
    {"t": "Gönül Dağı"},
    {"t": "Kuzgun"},
    {"t": "Ufak Tefek Cinayetler"},
    {"t": "Medcezir"},
    {"t": "Adını Feriha Koydum", "a": ["feriha"]},
  ] },
  cizgi: { name: 'Çizgi film', items: [
    {"t": "Sünger Bob", "a": ["spongebob", "sünger bob kare pantolon"]},
    {"t": "Tom ve Jerry", "a": ["tom and jerry", "tom jerry"]},
    {"t": "Şirinler", "a": ["smurfs"]},
    {"t": "Ben 10"},
    {"t": "Kral Şakir"},
    {"t": "Rafadan Tayfa"},
    {"t": "Pepee"},
    {"t": "Niloya"},
    {"t": "Keloğlan"},
    {"t": "Kukuli"},
    {"t": "Akıllı Tavşan Momo", "a": ["momo"]},
    {"t": "Scooby Doo"},
    {"t": "Simpsonlar", "a": ["simpsons", "the simpsons"]},
    {"t": "Sürekli Dizi", "a": ["regular show"]},
    {"t": "Kuzucuk Şon", "a": ["shaun the sheep", "koyun shaun"]},
    {"t": "Ninja Kaplumbağalar", "a": ["ninja turtles"]},
    {"t": "Mickey Mouse", "a": ["miki fare"]},
    {"t": "Donald Duck", "a": ["donald"]},
    {"t": "Pembe Panter", "a": ["pink panther"]},
    {"t": "Garfield"},
    {"t": "Temel Reis", "a": ["popeye"]},
    {"t": "Red Kit", "a": ["lucky luke"]},
    {"t": "Macera Zamanı", "a": ["adventure time"]},
    {"t": "Rick and Morty", "a": ["rick ve morty"]},
    {"t": "Gumball'un Muhteşem Dünyası", "a": ["gumball", "the amazing world of gumball"]},
    {"t": "Phineas ve Ferb", "a": ["phineas and ferb"]},
    {"t": "Avatar: Son Hava Bükücü", "a": ["avatar", "son hava bükücü", "avatar the last airbender", "last airbender", "aang"]},
    {"t": "Steven Universe"},
    {"t": "Powerpuff Kızları", "a": ["powerpuff girls", "powerpuff"]},
    {"t": "Dexter'ın Laboratuvarı", "a": ["dexters laboratory", "dexter laboratuvarı"]},
    {"t": "Johnny Bravo"},
    {"t": "Ed, Edd n Eddy", "a": ["ed edd eddy", "ed edd n eddy"]},
    {"t": "Courage", "a": ["cesur korkak köpek", "korkak köpek", "courage the cowardly dog"]},
    {"t": "Kim Possible"},
    {"t": "Çılgın Casuslar", "a": ["totally spies"]},
    {"t": "Winx Club", "a": ["winx"]},
    {"t": "Caillou"},
    {"t": "Kaşif Dora", "a": ["dora", "dora the explorer"]},
    {"t": "Tamirci Bob", "a": ["bob the builder"]},
    {"t": "Thomas ve Arkadaşları", "a": ["thomas"]},
    {"t": "Teletubbies"},
    {"t": "Heidi"},
    {"t": "Family Guy"},
    {"t": "South Park"},
    {"t": "Futurama"},
    {"t": "BoJack Horseman", "a": ["bojack"]},
    {"t": "Arcane"},
    {"t": "Gravity Falls"},
    {"t": "Hey Arnold"},
    {"t": "Rugrats"},
    {"t": "Ağaçkakan Woody", "a": ["woody woodpecker"]},
    {"t": "Bugs Bunny"},
    {"t": "Looney Tunes"},
    {"t": "Road Runner", "a": ["bip bip", "bip bip ve çakal"]},
    {"t": "Casper"},
    {"t": "Taş Devri", "a": ["flintstones", "the flintstones"]},
    {"t": "Winnie the Pooh", "a": ["ayı winnie", "winnie"]},
    {"t": "Peppa Pig", "a": ["peppa"]},
    {"t": "Maşa ile Koca Ayı", "a": ["masha and the bear", "maşa"]},
    {"t": "Pati Devriyesi", "a": ["paw patrol"]},
    {"t": "He-Man"},
    {"t": "Asteriks", "a": ["asterix"]},
    {"t": "Tenten", "a": ["tintin"]},
    {"t": "Voltran", "a": ["voltron"]},
    {"t": "Pinky ve Beyin", "a": ["pinky and the brain"]},
    {"t": "Pucca"},
    {"t": "Oggy ve Hamamböcekleri", "a": ["oggy and the cockroaches", "oggy"]},
    {"t": "Larva"},
    {"t": "Wallace ve Gromit", "a": ["wallace and gromit"]},
    {"t": "Danny Phantom"},
    {"t": "Jimmy Neutron"},
    {"t": "Mucize: Uğur Böceği ile Kara Kedi", "a": ["miraculous", "ladybug", "uğur böceği"]},
    {"t": "Teen Titans"},
    {"t": "Bluey"},
    {"t": "Bob'un Burgerleri", "a": ["bobs burgers"]},
    {"t": "Barbapapa"},
    {"t": "Arı Maya", "a": ["maya the bee"]},
    {"t": "Şeker Kız Candy", "a": ["candy"]},
  ] },
  anime: { name: 'Anime', items: [
    {"t": "Pokemon", "a": ["pokémon", "pikachu"]},
    {"t": "Doraemon"},
    {"t": "Naruto"},
    {"t": "Dragon Ball", "a": ["dragon ball z"]},
    {"t": "One Piece"},
    {"t": "Attack on Titan", "a": ["shingeki no kyojin", "titan"]},
    {"t": "Death Note"},
    {"t": "Demon Slayer", "a": ["kimetsu no yaiba"]},
    {"t": "Jujutsu Kaisen"},
    {"t": "One Punch Man"},
    {"t": "My Hero Academia", "a": ["boku no hero"]},
    {"t": "Hunter x Hunter", "a": ["hunter hunter"]},
    {"t": "Fullmetal Alchemist"},
    {"t": "Tokyo Ghoul"},
    {"t": "Bleach"},
    {"t": "Ruhların Kaçışı", "a": ["spirited away"]},
    {"t": "Komşum Totoro", "a": ["my neighbor totoro", "totoro"]},
    {"t": "Yürüyen Şato", "a": ["howls moving castle", "howl's moving castle"]},
    {"t": "Sailor Moon", "a": ["ay savaşçısı"]},
    {"t": "Kaptan Tsubasa", "a": ["captain tsubasa", "tsubasa"]},
    {"t": "Digimon"},
    {"t": "Yu-Gi-Oh!", "a": ["yugioh", "yu gi oh"]},
    {"t": "Beyblade"},
    {"t": "Bakugan"},
    {"t": "Chainsaw Man"},
    {"t": "Spy x Family", "a": ["spy family"]},
    {"t": "Your Name", "a": ["kimi no na wa"]},
    {"t": "Cowboy Bebop"},
    {"t": "Neon Genesis Evangelion", "a": ["evangelion"]},
    {"t": "Sword Art Online"},
    {"t": "Haikyuu"},
    {"t": "Blue Lock"},
    {"t": "Frieren"},
    {"t": "Solo Leveling"},
    {"t": "Dr. Stone", "a": ["dr stone"]},
    {"t": "JoJo", "a": ["jojo's bizarre adventure", "jojo bizarre adventure"]},
    {"t": "Detective Conan", "a": ["dedektif conan", "conan"]},
    {"t": "Hamtaro"},
    {"t": "Saint Seiya"},
    {"t": "Akira"},
  ] },
};
