// Bilgi Yarışması data. Photos are Wikimedia Commons files (free licences), loaded through Special:FilePath.
// [file, place name, country (or il for Turkey), lat, lng, inTurkey, mapOnly]
const QUIZ_PLACES = [
  ['Tour_Eiffel_Wikimedia_Commons_(cropped).jpg', 'Eyfel Kulesi, Paris', 'Fransa', 48.858, 2.294],
  ['Colosseo_2020.jpg', 'Kolezyum, Roma', 'İtalya', 41.890, 12.492],
  ['Front_view_of_Statue_of_Liberty_(cropped).jpg', 'Özgürlük Heykeli, New York', 'ABD', 40.689, -74.045],
  ['Taj_Mahal_(Edited).jpeg', 'Tac Mahal, Agra', 'Hindistan', 27.175, 78.042],
  ['The_Great_Wall_of_China_at_Jinshanling-edit.jpg', 'Çin Seddi', 'Çin', 40.431, 116.570],
  ['Machu_Picchu,_2023_(012).jpg', 'Machu Picchu', 'Peru', -13.163, -72.545],
  ['Christ_the_Redeemer_-_Cristo_Redentor.jpg', 'Kurtarıcı İsa Heykeli, Rio de Janeiro', 'Brezilya', -22.952, -43.210],
  ['Sydney_Australia._(21339175489).jpg', 'Sidney Opera Binası', 'Avustralya', -33.857, 151.215],
  ['Great_Pyramid_of_Giza_-_Pyramid_of_Khufu.jpg', 'Keops Piramidi, Giza', 'Mısır', 29.979, 31.134],
  ['Al_Deir_Petra.JPG', 'Petra', 'Ürdün', 30.329, 35.444],
  ['Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster,_London.jpg', 'Big Ben, Londra', 'Birleşik Krallık', 51.501, -0.125],
  ['SF_maig_2_cropped.jpg', 'Sagrada Família, Barselona', 'İspanya', 41.404, 2.174],
  ['Burj_Khalifa_(worlds_tallest_building)_and_the_Dubai_skyline_(25781049892).jpg', 'Burj Khalifa, Dubai', 'Birleşik Arap Emirlikleri', 25.197, 55.274],
  ['View_of_Mount_Fuji_from_Ōwakudani_20211202.jpg', 'Fuji Dağı', 'Japonya', 35.361, 138.727],
  ['Italy_-_Pisa_-_Leaning_Tower.jpg', 'Pisa Kulesi', 'İtalya', 43.723, 10.397],
  ['Schloss_Neuschwanstein_2013.jpg', 'Neuschwanstein Şatosu', 'Almanya', 47.558, 10.750],
  ["Saint_Basil's_Cathedral_in_Moscow.jpg", 'Aziz Vasil Katedrali, Moskova', 'Rusya', 55.753, 37.623],
  ['Stonehenge2007_07_30.jpg', 'Stonehenge', 'Birleşik Krallık', 51.179, -1.826],
  ['1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg', 'Akropolis, Atina', 'Yunanistan', 37.972, 23.726],
  ['Brandenburger_Tor_abends.jpg', 'Brandenburg Kapısı, Berlin', 'Almanya', 52.516, 13.378],
  ['Venezia_aerial_view.jpg', 'Venedik', 'İtalya', 45.441, 12.316],
  ['New_york_times_square-terabass.jpg', 'Times Meydanı, New York', 'ABD', 40.758, -73.986],
  ['Table_Mountain_DanieVDM.jpg', 'Masa Dağı, Cape Town', 'Güney Afrika', -33.963, 18.410],
  ['The_Atomium_during_civil_twilight_(DSCF1135).jpg', 'Atomium, Brüksel', 'Belçika', 50.895, 4.342],
  ['Mount_Rushmore_detail_view_(100MP).jpg', 'Rushmore Dağı', 'ABD', 43.879, -103.459],
  ['Tower_Bridge_at_Dawn.jpg', 'Tower Köprüsü, Londra', 'Birleşik Krallık', 51.506, -0.075],
  ['Karlův_most_Praha,_Staré_Město_20170810_007.jpg', 'Karlov Köprüsü, Prag', 'Çekya', 50.086, 14.411],
  ['Hallstatt_-_Zentrum_.JPG', 'Hallstatt', 'Avusturya', 47.562, 13.649],
  ['Cataratas_Victoria,_Zambia-Zimbabue,_2018-07-27,_DD_04.jpg', 'Victoria Şelalesi', 'Zambiya / Zimbabve', -17.925, 25.857, false, true],
  ['Moscow_Kremlin_(8281675670).jpg', 'Kremlin, Moskova', 'Rusya', 55.752, 37.618],
  ['Ha_Long_Bay_in_2019.jpg', 'Ha Long Körfezi', 'Vietnam', 20.910, 107.184],
  ['Aerial_Foz_de_Iguaçu_26_Nov_2005.jpg', 'İguazu Şelaleleri', 'Arjantin / Brezilya', -25.695, -54.437, false, true],
  ['Marina_Bay_Sands_(I).jpg', 'Marina Bay Sands', 'Singapur', 1.284, 103.861],
  ['Lake_Bled_from_the_Mountain.jpg', 'Bled Gölü', 'Slovenya', 46.364, 14.094],
  ['Cliffs-Of-Moher-OBriens-From-South.JPG', 'Moher Kayalıkları', 'İrlanda', 52.972, -9.426],
  ['Bagan,_Burma.jpg', 'Bagan', 'Myanmar', 21.172, 94.860],
  ['Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg', 'Kinkaku-ji, Kyoto', 'Japonya', 35.039, 135.729],
  ['Hollywood_sign_(8485145044).jpg', 'Hollywood Yazısı, Los Angeles', 'ABD', 34.134, -118.321],
  ['Las_Vegas_Strip_09_2017_4897.jpg', 'Las Vegas', 'ABD', 36.114, -115.173],
  ['AhuTongariki.JPG', 'Moai Heykelleri, Paskalya Adası', 'Şili', -27.126, -109.277],
  ['Sydney_Australia._(21339175489).jpg', 'Sidney Opera Binası', 'Avustralya', -33.857, 151.215],
  ['Angkor_Wat.jpg', 'Angkor Wat', 'Kamboçya', 13.412, 103.867],
  ['Chichen_Itza_3.jpg', 'Chichen Itza', 'Meksika', 20.684, -88.568],
  ['Golden_Gate_Bridge_as_seen_from_Battery_East.jpg', 'Golden Gate Köprüsü, San Francisco', 'ABD', 37.820, -122.478],
  ['The_Forbidden_City_-_View_from_Coal_Hill.jpg', 'Yasak Şehir, Pekin', 'Çin', 39.916, 116.397],
  ['Matterhorn_from_Domhütte_-_2.jpg', 'Matterhorn', 'İsviçre', 45.976, 7.659],
  ['Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg', 'Elhamra Sarayı, Granada', 'İspanya', 37.176, -3.588],
  ['Moraine_Lake_17092005.jpg', 'Moraine Gölü, Banff', 'Kanada', 51.322, -116.186],
  ['Mont-Saint-Michel_vu_du_ciel.jpg', 'Mont Saint-Michel', 'Fransa', 48.636, -1.511],
  ['ULURU.jpg', 'Uluru', 'Avustralya', -25.345, 131.036],
  ['The_walls_of_the_fortress_and_View_of_the_old_city._panorama.jpg', 'Dubrovnik', 'Hırvatistan', 42.641, 18.111],
  ['Petronas_Panorama_II_(4to3).jpg', 'Petronas Kuleleri, Kuala Lumpur', 'Malezya', 3.158, 101.712],
  ['CN_Tower_from_Puente_de_Luz,_Toronto,_Ontario,_2025-08-25_01.jpg', 'CN Kulesi, Toronto', 'Kanada', 43.643, -79.387],
  ['Hagia_Sophia_(228968325).jpeg', 'Ayasofya', 'İstanbul', 41.009, 28.980, true],
  ['Istanbul_(34223582516)_(cropped).jpg', 'Sultanahmet Camii', 'İstanbul', 41.005, 28.977, true],
  ['Galata_tower_01_23.jpg', 'Galata Kulesi', 'İstanbul', 41.026, 28.974, true],
  ['Istanbul_Kız_Kulesi_(54511155871)_(cropped).jpg', 'Kız Kulesi', 'İstanbul', 41.021, 29.004, true],
  ['Dolmabahce_Istanbul_Turkey.jpg', 'Dolmabahçe Sarayı', 'İstanbul', 41.039, 29.000, true],
  ['Cappadocia_balloon_trip,_Ortahisar_Castle_(11893715185).jpg', 'Kapadokya', 'Nevşehir', 38.643, 34.829, true],
  ['Pamukkale,_Denizli_2026_68.jpg', 'Pamukkale', 'Denizli', 37.920, 29.120, true],
  ['Mount_Nemrut_-_East_Terrace_(4961323529).jpg', 'Nemrut Dağı', 'Adıyaman', 37.981, 38.741, true],
  ['Ephesus_Celsus_Library_Façade.jpg', 'Efes Antik Kenti', 'İzmir', 37.939, 27.341, true],
  ['Sumela_From_Across_Valley.JPG', 'Sümela Manastırı', 'Trabzon', 40.690, 39.658, true],
  ["Ataturk's_Mausoleum_(6225341313).jpg", 'Anıtkabir', 'Ankara', 39.925, 32.837, true],
  ['Paragliding_view_oludeniz_-_panoramio_(2).jpg', 'Ölüdeniz', 'Muğla', 36.550, 29.115, true],
  ['Göbekli_Tepe,_Urfa.jpg', 'Göbekli Tepe', 'Şanlıurfa', 37.223, 38.922, true],
  ['Mardin,_Mardin_Merkez-Mardin,_Turkey_-_panoramio_(1).jpg', 'Mardin', 'Mardin', 37.313, 40.735, true],
  ['Uzungöl,_Trabzon.jpg', 'Uzungöl', 'Trabzon', 40.619, 40.295, true],
  ['20180107_Safranbolu_1945_(39101010504).jpg', 'Safranbolu', 'Karabük', 41.251, 32.692, true],
  ['Akdamar_Island_From_Near_Gevas.JPG', 'Akdamar Adası', 'Van', 38.341, 43.038, true],
  ['İshakpasa_Sarayı.jpg', 'İshak Paşa Sarayı', 'Ağrı', 39.520, 44.135, true],
  ['Mount_Ararat_and_the_Yerevan_skyline_in_spring_(50mm).jpg', 'Ağrı Dağı', 'Ağrı', 39.702, 44.298, true],
  ['Aspendos_Basilica_4728.jpg', 'Aspendos', 'Antalya', 36.939, 31.172, true],
  ['BodrumCastlesoutheast.jpg', 'Bodrum Kalesi', 'Muğla', 37.032, 27.429, true],
  ['Selimiye_Mosque_(15051985908)_(cropped).jpg', 'Selimiye Camii', 'Edirne', 41.678, 26.559, true],
].filter((p, i, a) => a.findIndex((x) => x[0] === p[0]) === i).map(([f, n, c, lat, lng, tr, mapOnly]) => ({ f, n, c, lat, lng, tr: !!tr, mapOnly: !!mapOnly }));

// Wrong-answer pools for photo questions.
const QUIZ_COUNTRIES = ['Fransa', 'İtalya', 'ABD', 'Hindistan', 'Çin', 'Peru', 'Brezilya', 'Avustralya', 'Mısır', 'Ürdün', 'Birleşik Krallık', 'İspanya',
  'Birleşik Arap Emirlikleri', 'Japonya', 'Almanya', 'Rusya', 'Yunanistan', 'Güney Afrika', 'Belçika', 'Çekya', 'Avusturya', 'Vietnam', 'Singapur',
  'Slovenya', 'İrlanda', 'Myanmar', 'Şili', 'Kamboçya', 'Meksika', 'İsviçre', 'Kanada', 'Hırvatistan', 'Malezya', 'Portekiz', 'Arjantin', 'Tayland',
  'Endonezya', 'Hollanda', 'Norveç', 'Fas', 'Güney Kore', 'Macaristan', 'Polonya'];
const QUIZ_ILLER = ['İstanbul', 'Ankara', 'İzmir', 'Antalya', 'Muğla', 'Nevşehir', 'Denizli', 'Adıyaman', 'Trabzon', 'Şanlıurfa', 'Mardin', 'Karabük', 'Van',
  'Ağrı', 'Edirne', 'Bursa', 'Konya', 'Rize', 'Kayseri', 'Erzurum', 'Gaziantep', 'Hatay', 'Çanakkale', 'Samsun', 'Eskişehir', 'Artvin', 'Aydın', 'Kars'];

const QUIZ_CAT_NAMES = { trdizi: '🇹🇷 Türk dizileri', dizi: '📺 Yabancı diziler', genel: '💡 Genel kültür' };

// [category, question, right answer, wrong 1, wrong 2, wrong 3]
const QUIZ_TEXT = [
  ['trdizi', "Kurtlar Vadisi'nin başrol karakteri kimdir?", 'Polat Alemdar', 'Memati Baş', 'Abdülhey Çoban', 'Süleyman Çakır'],
  ['trdizi', "Polat Alemdar'ı hangi oyuncu canlandırdı?", 'Necati Şaşmaz', 'Kenan İmirzalıoğlu', 'Kıvanç Tatlıtuğ', 'Erdal Beşikçioğlu'],
  ['trdizi', "Kurtlar Vadisi'nde Memati Baş'ı kim oynadı?", 'Gürkan Uygun', 'Necati Şaşmaz', 'Kenan İmirzalıoğlu', 'Haluk Bilginer'],
  ['trdizi', 'Behzat Ç. dizisi hangi şehirde geçer?', 'Ankara', 'İstanbul', 'İzmir', 'Eskişehir'],
  ['trdizi', "Behzat Ç.'yi hangi oyuncu canlandırdı?", 'Erdal Beşikçioğlu', 'Ali Atay', 'Uğur Yücel', 'Haluk Bilginer'],
  ['trdizi', "Ezel'i hangi oyuncu canlandırdı?", 'Kenan İmirzalıoğlu', 'Kıvanç Tatlıtuğ', 'Burak Özçivit', 'Engin Akyürek'],
  ['trdizi', "Ezel dizisinde Ezel'in eski adı neydi?", 'Ömer', 'Cengiz', 'Kenan', 'Ali'],
  ['trdizi', 'Muhteşem Yüzyıl hangi padişahın dönemini anlatır?', 'Kanuni Sultan Süleyman', 'Fatih Sultan Mehmet', 'Yavuz Sultan Selim', 'IV. Murat'],
  ['trdizi', "Muhteşem Yüzyıl'da Hürrem Sultan'ı kim oynadı?", 'Meryem Uzerli', 'Nurgül Yeşilçay', 'Beren Saat', 'Tuba Büyüküstün'],
  ['trdizi', "Diriliş: Ertuğrul'un devamı olan dizi hangisi?", 'Kuruluş: Osman', 'Payitaht Abdülhamid', 'Alparslan: Büyük Selçuklu', 'Mehmed: Fetihler Sultanı'],
  ['trdizi', "Diriliş: Ertuğrul'da Ertuğrul Bey'i kim oynadı?", 'Engin Altan Düzyatan', 'Burak Özçivit', 'Kıvanç Tatlıtuğ', 'Necati Şaşmaz'],
  ['trdizi', "Kuruluş: Osman'da Osman Bey'i kim oynadı?", 'Burak Özçivit', 'Engin Altan Düzyatan', 'Kenan İmirzalıoğlu', 'Barış Arduç'],
  ['trdizi', "Çukur'da Yamaç Koçovalı'yı kim oynadı?", 'Aras Bulut İynemli', 'Erkan Kolçak Köstendil', 'Kerem Bürsin', 'Çağatay Ulusoy'],
  ['trdizi', "Aşk-ı Memnu'da Behlül'ü kim oynadı?", 'Kıvanç Tatlıtuğ', 'Kenan İmirzalıoğlu', 'Çağatay Ulusoy', 'Burak Özçivit'],
  ['trdizi', 'Aşk-ı Memnu kimin romanından uyarlandı?', 'Halit Ziya Uşaklıgil', 'Reşat Nuri Güntekin', 'Orhan Pamuk', 'Yaşar Kemal'],
  ['trdizi', 'Yaprak Dökümü kimin romanından uyarlandı?', 'Reşat Nuri Güntekin', 'Halit Ziya Uşaklıgil', 'Sabahattin Ali', 'Ahmet Hamdi Tanpınar'],
  ['trdizi', "Avrupa Yakası'nın yazarı kimdir?", 'Gülse Birsel', 'Yılmaz Erdoğan', 'Cem Yılmaz', 'Ata Demirer'],
  ['trdizi', "Leyla ile Mecnun'da Mecnun'u kim oynadı?", 'Ali Atay', 'Serkan Keskin', 'Ahmet Mümtaz Taylan', 'Cengiz Bozkurt'],
  ['trdizi', 'Bir Başkadır hangi platformda yayınlandı?', 'Netflix', 'BluTV', 'Exxen', 'Disney+'],
  ['trdizi', 'Netflix\'in ilk Türk yapımı dizisi hangisidir?', 'Hakan: Muhafız', 'Bir Başkadır', 'Atiye', 'Kulüp'],
  ['trdizi', 'Yargı dizisinde Ilgaz ve Ceylin hangi meslekleri yapar?', 'Savcı ve avukat', 'Doktor ve hemşire', 'Polis ve gazeteci', 'Öğretmen ve müdür'],
  ['trdizi', "Kiralık Aşk'ta Defne'yi kim oynadı?", 'Elçin Sangu', 'Hande Erçel', 'Demet Özdemir', 'Neslihan Atagül'],
  ['trdizi', "Erkenci Kuş'ta Can Divit'i kim oynadı?", 'Can Yaman', 'Barış Arduç', 'Kerem Bürsin', 'Çağatay Ulusoy'],
  ['trdizi', "Sen Çal Kapımı'da Serkan Bolat'ı kim oynadı?", 'Kerem Bürsin', 'Can Yaman', 'Barış Arduç', 'Burak Deniz'],
  ['trdizi', 'Medcezir hangi yabancı dizinin uyarlamasıdır?', 'The O.C.', 'Gossip Girl', 'Friends', "Grey's Anatomy"],
  ['trdizi', "Kara Sevda'da Kemal'i kim oynadı?", 'Burak Özçivit', 'Kıvanç Tatlıtuğ', 'Kerem Bürsin', 'Engin Akyürek'],
  ['trdizi', "Çocuklar Duymasın'daki anne-babanın adları nedir?", 'Haluk ve Meltem', 'Selim ve Sevgi', 'Cem ve Nil', 'Ali ve Ayşe'],
  ['trdizi', "Yalı Çapkını'nda Ferit Korhan'ı kim oynadı?", 'Mert Ramazan Demir', 'Çağatay Ulusoy', 'Can Yaman', 'Barış Arduç'],
  ['trdizi', "Ramo dizisinde Ramo'yu kim oynadı?", 'Murat Yıldırım', 'Kıvanç Tatlıtuğ', 'Aras Bulut İynemli', 'Engin Akyürek'],
  ['trdizi', "Şahsiyet'te Agah Beyoğlu'nu kim oynadı?", 'Haluk Bilginer', 'Şener Şen', 'Uğur Yücel', 'Erdal Beşikçioğlu'],
  ['trdizi', "Fatmagül'ün Suçu Ne?'de Kerim'i kim oynadı?", 'Engin Akyürek', 'Kıvanç Tatlıtuğ', 'Burak Özçivit', 'Kenan İmirzalıoğlu'],
  ['trdizi', "Kuzey Güney'de Kuzey'i Kıvanç Tatlıtuğ oynadı. Güney'i kim oynadı?", 'Buğra Gülsoy', 'Burak Özçivit', 'Engin Akyürek', 'Çağatay Ulusoy'],

  ['dizi', "Breaking Bad'de Walter White'ın asıl mesleği nedir?", 'Kimya öğretmeni', 'Doktor', 'Avukat', 'Polis'],
  ['dizi', "Breaking Bad'de Walter White'ı kim oynadı?", 'Bryan Cranston', 'Aaron Paul', 'Bob Odenkirk', 'Jon Hamm'],
  ['dizi', "Breaking Bad'deki avukat karakterin kendi dizisinin adı nedir?", 'Better Call Saul', 'Ozark', 'Narcos', 'Suits'],
  ['dizi', "Game of Thrones'ta Jon Snow hangi ailenin yanında büyüdü?", 'Stark', 'Lannister', 'Targaryen', 'Baratheon'],
  ['dizi', "Game of Thrones'ta Daenerys'in kaç ejderhası vardı?", '3', '2', '4', '5'],
  ['dizi', 'Game of Thrones hangi kitap serisinden uyarlandı?', 'Buz ve Ateşin Şarkısı', 'Yüzüklerin Efendisi', 'Witcher', 'Narnia Günlükleri'],
  ['dizi', 'Friends dizisi hangi şehirde geçer?', 'New York', 'Los Angeles', 'Chicago', 'Boston'],
  ['dizi', "Friends'te Ross'un mesleği nedir?", 'Paleontolog', 'Doktor', 'Aşçı', 'Oyuncu'],
  ['dizi', 'Stranger Things hangi kasabada geçer?', 'Hawkins', 'Springfield', 'Riverdale', 'Derry'],
  ['dizi', "Stranger Things'te Eleven'ın en sevdiği yiyecek nedir?", 'Eggo waffle', 'Pizza', 'Hamburger', 'Patlamış mısır'],
  ['dizi', "La Casa de Papel'de soygunu planlayan karakter kimdir?", 'Profesör', 'Berlin', 'Tokyo', 'Nairobi'],
  ['dizi', "La Casa de Papel'de karakterlere neyin isimleri verilir?", 'Şehirlerin', 'Ülkelerin', 'Gezegenlerin', 'Renklerin'],
  ['dizi', 'Squid Game hangi ülkenin dizisidir?', 'Güney Kore', 'Japonya', 'Çin', 'Tayland'],
  ['dizi', "Squid Game'de yarışmacılar hangi renk eşofman giyer?", 'Yeşil', 'Mavi', 'Kırmızı', 'Sarı'],
  ['dizi', "Sherlock'ta Sherlock Holmes'u kim oynadı?", 'Benedict Cumberbatch', 'Martin Freeman', 'Tom Hiddleston', 'Robert Downey Jr.'],
  ['dizi', "Sherlock'ta Dr. Watson'ı kim oynadı?", 'Martin Freeman', 'Benedict Cumberbatch', 'Andrew Scott', 'Jude Law'],
  ['dizi', 'Peaky Blinders hangi şehirde geçer?', 'Birmingham', 'Londra', 'Manchester', 'Liverpool'],
  ['dizi', 'The Office (ABD) hangi şirkette geçer?', 'Dunder Mifflin', 'Wernham Hogg', 'Pied Piper', 'Sterling Cooper'],
  ['dizi', 'Dark dizisi hangi ülkenin yapımıdır?', 'Almanya', 'İspanya', 'Danimarka', 'Norveç'],
  ['dizi', 'Wednesday hangi ailenin kızıdır?', 'Addams', 'Simpson', 'Munster', 'Griffin'],
  ['dizi', "The Walking Dead'de insanlığı ne tehdit eder?", 'Zombiler', 'Uzaylılar', 'Robotlar', 'Vampirler'],
  ['dizi', "How I Met Your Mother'da hikâyeyi anlatan karakter kimdir?", 'Ted Mosby', 'Barney Stinson', 'Marshall Eriksen', 'Robin Scherbatsky'],
  ['dizi', "The Big Bang Theory'de Sheldon'ın mesleği nedir?", 'Fizikçi', 'Biyolog', 'Mühendis', 'Doktor'],
  ['dizi', "Dexter'ın gündüz işi nedir?", 'Kan izi analisti', 'Avukat', 'Cerrah', 'Gazeteci'],
  ['dizi', "The Mentalist'te Patrick Jane'in eski işi neydi?", 'Sahte medyum', 'Sihirbaz', 'Avukat', 'Cerrah'],
  ['dizi', "Dr. House'un asıl uzmanlığı nedir?", 'Teşhis koymak', 'Kalp cerrahisi', 'Psikiyatri', 'Diş hekimliği'],
  ['dizi', 'The Simpsons hangi kasabada geçer?', 'Springfield', 'Hawkins', 'South Park', 'Quahog'],
  ['dizi', "Rick and Morty'de Rick, Morty'nin nesidir?", 'Dedesi', 'Babası', 'Amcası', 'Ağabeyi'],
  ['dizi', 'The Crown hangi ülkenin kraliyet ailesini anlatır?', 'Birleşik Krallık', 'İspanya', 'Hollanda', 'İsveç'],
  ['dizi', "Prison Break'te Michael Scofield neden hapse girer?", 'Abisini kaçırmak için', 'Para çalmak için', 'Babasını bulmak için', 'Yanlışlıkla'],
  ['dizi', "Narcos'un ilk sezonları hangi uyuşturucu baronunu anlatır?", 'Pablo Escobar', 'El Chapo', 'Al Capone', 'Tony Montana'],
  ['dizi', "The Witcher'da Geralt'ı ilk üç sezonda kim oynadı?", 'Henry Cavill', 'Chris Hemsworth', 'Jason Momoa', 'Liam Hemsworth'],

  ['genel', 'Bir yılda kaç hafta vardır?', '52', '48', '50', '54'],
  ['genel', '34 plaka hangi ilimize aittir?', 'İstanbul', 'İzmir', 'Ankara', 'Bursa'],
  ['genel', '35 plaka hangi ilimize aittir?', 'İzmir', 'Antalya', 'Bursa', 'Konya'],
  ['genel', '06 plaka hangi ilimize aittir?', 'Ankara', 'Adana', 'Antalya', 'Artvin'],
  ['genel', '61 plaka hangi ilimize aittir?', 'Trabzon', 'Rize', 'Samsun', 'Ordu'],
  ['genel', '07 plaka hangi ilimize aittir?', 'Antalya', 'Aydın', 'Adana', 'Muğla'],
  ['genel', '42 plaka hangi ilimize aittir?', 'Konya', 'Kayseri', 'Karaman', 'Sivas'],
  ['genel', 'Su deniz seviyesinde kaç derecede kaynar?', '100°C', '90°C', '80°C', '120°C'],
  ['genel', 'Futbolda sahada bir takımın kaç oyuncusu olur?', '11', '10', '9', '12'],
  ['genel', 'Basketbolda sahada bir takımın kaç oyuncusu olur?', '5', '6', '7', '4'],
  ['genel', 'Voleybolda sahada bir takımın kaç oyuncusu olur?', '6', '5', '7', '8'],
  ['genel', 'Gökkuşağında kaç renk vardır?', '7', '5', '6', '8'],
  ['genel', 'Bir saatte kaç saniye vardır?', '3600', '360', '6000', '1200'],
  ['genel', 'Güneş Sistemi\'nin en büyük gezegeni hangisidir?', 'Jüpiter', 'Satürn', 'Neptün', 'Dünya'],
  ['genel', 'Güneş Sistemi\'nde kaç gezegen vardır?', '8', '9', '7', '10'],
  ['genel', 'Hangi gezegen "Kızıl Gezegen" olarak bilinir?', 'Mars', 'Venüs', 'Jüpiter', 'Merkür'],
  ['genel', 'İnsan vücudunun en büyük organı hangisidir?', 'Deri', 'Karaciğer', 'Akciğer', 'Beyin'],
  ['genel', 'Yetişkin bir insanın kaç dişi vardır?', '32', '28', '30', '36'],
  ['genel', "Türkiye'de kaç il vardır?", '81', '80', '79', '82'],
  ['genel', "Türkiye'nin en büyük gölü hangisidir?", 'Van Gölü', 'Tuz Gölü', 'Beyşehir Gölü', 'Eğirdir Gölü'],
  ['genel', "Türkiye'nin en yüksek dağı hangisidir?", 'Ağrı Dağı', 'Erciyes Dağı', 'Uludağ', 'Kaçkar Dağı'],
  ['genel', "Tamamı Türkiye'de olan en uzun nehir hangisidir?", 'Kızılırmak', 'Fırat', 'Dicle', 'Sakarya'],
  ['genel', 'Peribacaları ile ünlü il hangisidir?', 'Nevşehir', 'Denizli', 'Konya', 'Kayseri'],
  ['genel', 'Cumhuriyet hangi yıl ilan edildi?', '1923', '1920', '1919', '1938'],
  ['genel', 'İstanbul hangi yıl fethedildi?', '1453', '1071', '1299', '1517'],
  ['genel', "İstiklal Marşı'nın yazarı kimdir?", 'Mehmet Akif Ersoy', 'Namık Kemal', 'Nazım Hikmet', 'Yahya Kemal Beyatlı'],
  ['genel', 'Mona Lisa tablosunu kim yaptı?', 'Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Michelangelo'],
  ['genel', "Romeo ve Juliet'i kim yazdı?", 'William Shakespeare', 'Victor Hugo', 'Lev Tolstoy', 'Dante Alighieri'],
  ['genel', "Japonya'nın para birimi nedir?", 'Yen', 'Won', 'Yuan', 'Rupi'],
  ['genel', 'Hangisi bir meyve değildir?', 'Patates', 'Elma', 'Muz', 'Kiraz'],
  ['genel', 'Pizza hangi ülkenin mutfağından çıkmıştır?', 'İtalya', 'Fransa', 'ABD', 'Yunanistan'],
  ['genel', 'Suyun kimyasal formülü nedir?', 'H₂O', 'CO₂', 'O₂', 'NaCl'],
  ['genel', "Ay'a ayak basan ilk insan kimdir?", 'Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'Elon Musk'],
  ['genel', 'Artık yıllarda Şubat kaç gün çeker?', '29', '28', '30', '31'],
  ['genel', 'Maraton koşusu yaklaşık kaç kilometredir?', '42 km', '21 km', '50 km', '30 km'],
  ['genel', 'En hızlı kara hayvanı hangisidir?', 'Çita', 'Aslan', 'At', 'Ceylan'],
  ['genel', 'Kırmızı ile sarı karışınca hangi renk olur?', 'Turuncu', 'Yeşil', 'Mor', 'Kahverengi'],
  ['genel', 'Bir haftada kaç saat vardır?', '168', '144', '172', '186'],
  ['genel', "Türkiye'nin uluslararası telefon kodu nedir?", '+90', '+44', '+49', '+30'],
  ['genel', 'Instagram hangi şirkete aittir?', 'Meta', 'Google', 'Apple', 'Microsoft'],
  ['genel', "Avustralya'nın başkenti neresidir?", 'Kanberra', 'Sidney', 'Melbourne', 'Perth'],
  ['genel', "Kanada'nın başkenti neresidir?", 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
  ['genel', 'En küçük asal sayı hangisidir?', '2', '1', '3', '0'],
  ['genel', 'Normal bir futbol maçı kaç dakika sürer?', '90', '80', '100', '120'],
  ['genel', 'Satrançta en güçlü taş hangisidir?', 'Vezir', 'Kale', 'At', 'Fil'],
  ['genel', "Dünyanın en yüksek dağı hangisidir?", 'Everest', 'K2', 'Kilimanjaro', 'Ağrı Dağı'],
  ['genel', 'Bir düzine kaç tanedir?', '12', '10', '6', '20'],
  ['genel', 'Türk lirasının simgesi hangisidir?', '₺', '$', '€', '£'],
  ['genel', "2023'ten beri dünyanın en kalabalık ülkesi hangisidir?", 'Hindistan', 'Çin', 'ABD', 'Endonezya'],
  ['genel', "WhatsApp'ta mesaj okununca tikler hangi renge döner?", 'Mavi', 'Yeşil', 'Gri', 'Kırmızı'],
  ['genel', 'Hangisi memeli değildir?', 'Penguen', 'Yunus', 'Yarasa', 'Balina'],
  ['genel', 'Bir üçgenin iç açıları toplamı kaç derecedir?', '180°', '360°', '90°', '270°'],
  ['genel', 'Dünyada en çok kahve üreten ülke hangisidir?', 'Brezilya', 'Kolombiya', 'Etiyopya', 'Türkiye'],
  ['genel', 'Dünyanın en büyük okyanusu hangisidir?', 'Büyük Okyanus (Pasifik)', 'Atlas Okyanusu', 'Hint Okyanusu', 'Arktik Okyanusu'],
  ['genel', "Fenerbahçe'nin renkleri nelerdir?", 'Sarı-lacivert', 'Sarı-kırmızı', 'Siyah-beyaz', 'Bordo-mavi'],
  ['genel', 'Dinlenme halindeki bir yetişkinin kalbi dakikada kaç kez atar?', '60-100', '20-40', '120-160', '200 üstü'],
].map(([c, q, a, ...w]) => ({ c, q, a, w }));
